export const REQUEST_FREE_APPS = 'REQUEST_FREE_APPS';
export const RECEIVE_FREE_APPS = 'RECEIVE_FREE_APPS';
export const FILTER_FREE_APPS = 'FILTER_FREE_APPS';
export const LOAD_MORE_FREE_APPS = 'LOAD_MORE_FREE_APPS';